
# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Jose"
license = "MIT"
theme = "tale"
licenselink = "https://github.com/nanxiaobei/hugo-paper/blob/master/LICENSE"
description = "A personal blog"
homepage = "jsameijeiras.eu"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog", "Economics","Data Analytics"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"

[author]
  name = "nanxiaobei"
  homepage = "https://mrlee.me/"

# If porting an existing theme
[original]
  name = "jsameijerias"
  homepage = ""
  repo = ""